### ISSUE TITLE
Layout error on following and followers

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#658]
As reported by sam:

"There is a little problem on the users 'following you' page. It seems that if a user name is of a certain length it will display below the avatar, but the next row does not compensate for this, so we get a page [...]"  -> with broken layout
Workaround can probably be using "overflow:hidden" as pointed out by Iwan

**Comment by efx** [comment]
Applying these styles to the http://www.freesound.org/people/person/followers/ page should also solve the broken layout issue. I would also prefix the `.content_box` rules with another class or ID specific to the followers page so you do not get conflicts.
```css
.content_box ul {
  padding-left: 0;
}
.followers_page_user_info {
    display: block;
    float: left;
    height: 50px;
    margin-right: 10px;
    width: 170px;
}
.content_box {
    width: 540px;
}
```
